M48
; DRILL file {KiCad (6.0.0)} date Thu Dec 30 22:07:17 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-12-30T22:07:17+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0256
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0315
%
G90
G05
T1
X4.312Y-3.87
X4.318Y-3.506
X4.714Y-3.41
X4.714Y-3.63
T2
X5.2Y-3.4
X5.2Y-3.45
X5.2Y-3.5
X5.2Y-3.55
T3
X4.04Y-3.5
X4.04Y-3.6
X4.04Y-3.7
X4.04Y-3.8
T0
M30
