M48
; DRILL file {KiCad (6.0.0)} date Sun Jan  9 12:53:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-09T12:53:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0256
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1181
%
G90
G05
T1
X4.29Y-3.82
X4.318Y-3.506
X4.714Y-3.63
X4.76Y-3.44
X4.924Y-3.498
T2
X5.2Y-3.4
X5.2Y-3.45
X5.2Y-3.5
X5.2Y-3.55
T3
X4.04Y-3.5
X4.04Y-3.6
X4.04Y-3.7
X4.04Y-3.8
T4
X5.015Y-3.65
T0
M30
